version: '2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  web:
    build: .
    command: bundle exec hanami s -p 2300 --host '0.0.0.0'
    volumes:
      - .:/geeami
    ports:
      - "3020:3020"
      - "2300:2300"
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes_from:
      - bundle
    environment:
      - SERVE_STATIC_ASSETS=true
      - WEB_SESSIONS_SECRET=834502c4209e608102ecb1ead9a55134002567068223fbd3f1a56f13d4e9a0b9
      - WEBPACK_DEV_SERVER_HOST=0.0.0.0
  bundle:
    image: geeami_web
    volumes:
      - /bundle
